mutation SignUp($signUpInput: SignUpInput!) {
  signUp(signUpInput: $signUpInput)
}

mutation SignIn($signInInput: SignInInput!) {
  signIn(signInInput: $signInInput) {
    accessToken
    user {
      userId
      name
      profileImg
    }
  }
}

mutation SignOut {
  signOut
}

mutation ChangePassword($input: ChangePasswordInput!) {
  changePassword(input: $input) {
    userId
    name
    profileImg
  }
}

mutation SavePlaylist($mutatePlaylistInput: MutatePlaylistInput!) {
  savePlaylist(mutatePlaylistInput: $mutatePlaylistInput)
}

mutation RemovePlaylist($playlistId: String!) {
  removePlaylist(playlistId: $playlistId)
}

mutation ReadPlaylist($link: String!) {
  readPlaylist(link: $link) {
    title
    artist
    album
    thumbnail
  }
}

mutation ConvertToYoutubePlaylist(
  $authorizationCode: String
  $listJSON: [PlaylistJSONInput!]!
  $state: String
) {
  convertToYoutubePlaylist(
    authorizationCode: $authorizationCode
    listJSON: $listJSON
    state: $state
  ) {
    __typename
    ... on ConvertedPlaylist {
      success
      message
      playlistId
      playlistName
      playlistUrl
    }
    ... on AuthRequiredResponse {
      needsAuth
      authUrl
      apiDomain
    }
  }
}

mutation ConvertToSpotifyPlaylist(
  $authorizationCode: String
  $listJSON: [PlaylistJSONInput!]!
  $state: String
) {
  convertToSpotifyPlaylist(
    authorizationCode: $authorizationCode
    listJSON: $listJSON
    state: $state
  ) {
    __typename
    ... on ConvertedPlaylist {
      success
      message
      playlistId
      playlistName
      playlistUrl
    }
    ... on AuthRequiredResponse {
      needsAuth
      authUrl
      apiDomain
    }
  }
}

mutation UpdateUser($updateUserInput: UpdateUserInput!) {
  updateUser(updateUserInput: $updateUserInput)
}

mutation SaveStatistic($saveStatisticInput: MutateStatisticInput!) {
  saveStatistic(saveStatisticInput: $saveStatisticInput)
}

mutation UpdateStatistic($updateStatisticInput: MutateStatisticInput!) {
  updateStatistic(updateStatisticInput: $updateStatisticInput) {
    albumRankJson {
      first
      second
      third
    }
    artistRankJson {
      first
      second
      third
    }
    titleRankJson {
      first
      second
      third
    }
    updatedAt
  }
}

mutation RemoveStatistic($userId: ID!) {
  removeStatistic(userId: $userId)
}

mutation CheckId($id: String!) {
  checkId(id: $id)
}

mutation CheckPassword($password: String!) {
  checkPassword(password: $password)
}

mutation UpdatePlaylist($mutatePlaylistInput: MutatePlaylistInput!) {
  updatePlaylist(mutatePlaylistInput: $mutatePlaylistInput)
}
