query GetUser {
  user {
    userId
    name
    profileImg
  }
}

query GetPlaylist($playlistId: String!) {
  playlist(playlistId: $playlistId) {
    playlistId
    name
    createdAt
    thumbnail
    userId
    listJson {
      title
      artist
      album
      thumbnail
    }
  }
}

query GetPlaylistsByUser(
  $after: String
  $limit: Int!
  $orderBy: String!
  $userId: String!
) {
  playlistsByUser(
    after: $after
    limit: $limit
    orderBy: $orderBy
    userId: $userId
  ) {
    edges {
      cursor
      node {
        playlistId
        name
        createdAt
        thumbnail
        userId
        listJson {
          title
          artist
          album
          thumbnail
        }
      }
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}

query GetStatistic($userId: ID!) {
  statistic(userId: $userId) {
    albumRankJson {
      first
      second
      third
    }
    artistRankJson {
      first
      second
      third
    }
    titleRankJson {
      first
      second
      third
    }
    updatedAt
  }
}
